version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    networks:
      - gobnb
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/app
    depends_on:
      - db
    networks:
      - gobnb
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gobnb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gobnb
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - gobnb
volumes:
  # api:
  database_postgres:
networks:
  gobnb:
