version: '3.7'
services:
  # proxy:
  #   build:
  #     context: ./proxy
  #     dockerfile: Dockerfile
  #   restart: always
  #   networks:
  #     - gobnb
  #   ports:
  #     - 80:80
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   networks:
  #     - gobnb
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airbnb
    volumes:
      - ./server:/app
    networks:
      - airbnb
    restart: always
    volumes:
      - ./server/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      # - proxy
      - db
    networks:
      - airbnb
    ports:
      - 80:80
    volumes:
      - ./server:/app

volumes:
  # api:
  database_postgres:

networks:
  airbnb:
