version: '3.7'

services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: dev.Dockerfile
  #   networks:
  #     - airbnb
  #   ports:
  #     - 80:3000
  #   stdin_open: true
  #   volumes:
  #     - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/app
    depends_on:
      - db
    networks:
      - airbnb
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airbnb
    networks:
      - airbnb
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./server/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  # api:
  database_postgres:
networks:
  airbnb:
