version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - database_postgres:/var/lib/postgresql/data

  server:
    build: .
    image: gonebnb_server
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db

volumes:
  api:
  database_postgres:
