version: '3.7'
services:
  # proxy:
  #   build:
  #     context: ./proxy
  #     dockerfile: Dockerfile
  #   restart: always
  #   networks:
  #     - gobnb
  #   ports:
  #     - 80:80
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   networks:
  #     - gobnb
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airbnb
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - airbnb
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      # - proxy
      - db
    networks:
      - airbnb

volumes:
  api:
  database_postgres:

networks:
  airbnb:
