version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - gonebnb

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db
    networks:
      - gonebnb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - gonebnb
    stdin_open: true

volumes:
  api:
  database_postgres:

networks:
  gonebnb:
    driver: bridge
