export const $PROTOTYPE = {
  getstarted: 'getstarted',
  room: 'room',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  location: 'location',
  amenities: 'amenities',
  spaces: 'spaces',
  description: 'description',
  title: 'title',
  phone: 'phone',
  requirements: 'requirements',
  rules: 'rules',
  checkin: 'checkin',
  advance: 'advance',
  period: 'period',
  price: 'price',
  scenarios: 'scenarios',
  photos: 'photos',
};
