export const $INPUT = {
  email: 'email',
  password: 'password',
  name: 'name',
  birthdate: 'birthdate',
  phone: 'phone',
  region: 'region',
  place: 'place',
  guests: 'guests',
  address: 'address',
  select: 'select',
  radio: 'radio',
  counter: 'counter',
  text: 'text',
  checkbox: 'checkbox',
  textarea: 'textarea',
  limit: 'limit',
  verify: 'verify',
  closed: 'closed',
  price: 'price',
  photo: 'photo',
  another: 'another',
};
