version: 2.1

aliases:
  - &docker-image
    docker:
      - image: circleci/node:10

  - &typescript
    run:
      name: Install typescript global
      command: yarn global add typescript

  - &install
    run:
      name: Install dependencies
      command: yarn

  - &build
    run:
      name: Build package
      command: yarn build

  - &test
    run:
      name: Test
      command: yarn test:ci

  - &docker-build-auth
    run:
      name: Building Docker Image
      command: docker build

  - &login
    run:
      name: Log in
      command: docker login -u $DOCKER_USER -p $DOCKER_PASS

  - &docker-push-auth
    run:
      name: Pushing to docker hub
      command: docker push kokiebisu/nextbnb-auth

  - &install-auth:
    run:
      name: Install 
      command: cd services/auth && yarn

  - &build-auth:
    run:
      name: Build Auth Service
      command: cd services/auth && yarn build

commands:
  install:
    steps:
      - checkout:
          path: ~/airbnb
      - *install

  build:
    steps:
      - checkout:
          path: ~/airbnb
      - *build

  test:
    steps:
      - checkout:
          path: ~/airbnb
      - *typescript
      - *install
      - *install-auth
      - *build-auth
      - *test

jobs:
  test-auth:
    docker:
      - image: circleci/node:10

    working_directory: ~/airbnb
    steps:
      - test

workflows:
  version: 2
  auth-service:
    jobs:
      - test-auth
