version: 2.1
executors:
  default-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/airbnb
commands:
  prepare:
    description: "Installs and builds the lerna environment"
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Install lerna
          command: yarn global add lerna -D -W
      - run:
          name: Install dependencies
          command: yarn bootstrap
      - run:
          name: Build packages
          command: yarn compile:packages
  docker-setup:
    parameters:
      image-name:
        type: string
      directory-name:
        type: string
    description: "Builds the docker image and pushes up to Dockerhub"
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Building <<parameters.directory-name>> image
          command: docker build -t <<parameters.image-name>> -f ./services/<<parameters.directory-name>>/Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push <<parameters.image-name>>

jobs:
  test-auth:
    executor: default-executor
    steps:
      - prepare
      - run:
          name: Testing
          command: yarn test:auth
  # push-prod-auth:
  #   working_directory: ~/airbnb
  #   machine: true
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: building auth image
  #         command: docker build -t kokiebisu/nextbnb-auth -f ./services/auth/Dockerfile .
  #     - run:
  #         name: Log in
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Pushing to docker hub
  #         command: docker push kokiebisu/nextbnb-auth
  # push-dev-auth:
  #   working_directory: ~/airbnb
  #   machine: true
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: building auth image
  #         command: docker build -t kokiebisu/nextbnb-auth-dev -f ./services/auth/dev.Dockerfile .
  #     - run:
  #         name: Log in
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Pushing to docker hub
  #         command: docker push kokiebisu/nextbnb-auth-dev
  test-stays:
    executor: default-executor
    steps:
      - prepare
      - run:
          name: Testing
          command: yarn test:stays
  push-prod-stays:
    working_directory: ~/airbnb
    machine: true
    steps:
      - docker-setup:
          image-name: "kokiebisu/nextbnb-stays"
          directory-name: "stays"
      # - run:
      #     name: building stays image
      #     command: docker build -t kokiebisu/nextbnb-stays -f ./services/stays/Dockerfile .
      # - run:
      #     name: Log in
      #     command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # - run:
      #     name: Pushing to docker hub
      #     command: docker push kokiebisu/nextbnb-stays
  # push-dev-stays:
  #   working_directory: ~/airbnb
  #   machine: true
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: building stays image
  #         command: docker build -t kokiebisu/nextbnb-stays-dev -f ./services/stays/dev.Dockerfile .
  #     - run:
  #         name: Log in
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Pushing to docker hub
  #         command: docker push kokiebisu/nextbnb-stays-dev
  test-web:
    executor: default-executor
    steps:
      - prepare
      - run:
          name: Testing
          command: yarn test:web
  # storybook:
  #   working_directory: ~/airbnb/ui/web
  #   docker:
  #     - image: circleci/node:10
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: Installing dependencies
  #         command: yarn install
  #     - run:
  #         name: Testing snapshot
  #         command: yarn snapshot
  #     - run:
  #         name: Comparing snapshots
  #         command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes
  # push-prod-web:
  #   working_directory: ~/airbnb
  #   machine: true
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: Building web image
  #         command: docker build -t kokiebisu/nextbnb-web -f ./ui/web/Dockerfile .
  #     - run:
  #         name: Log in
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Pushing to docker hub
  #         command: docker push kokiebisu/nextbnb-web
  # push-dev-web:
  #   working_directory: ~/airbnb
  #   machine: true
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: Building web image
  #         command: docker build -t kokiebisu/nextbnb-web-dev -f ./ui/web/dev.Dockerfile .
  #     - run:
  #         name: Log in
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Pushing to docker hub
  #         command: docker push kokiebisu/nextbnb-web-dev

workflows:
  version: 2
  auth:
    jobs:
      - test-auth:
          filters:
            branches:
              ignore:
                - develop
        # - push-dev-auth:
        #     requires:
        #       - test-auth
        #     filters:
        #       branches:
        #         ignore:
        #           - develop
        # - push-prod-auth:
        #     filters:
        #       branches:
        #         only:
        #           - develop
  stays:
    jobs:
      - test-stays:
          filters:
            branches:
              ignore:
                - develop
      #     - push-dev-stays:
      #         requires:
      #           - test-stays
      #         filters:
      #           branches:
      #             ignore:
      #               - develop
      - push-prod-stays:
          # filters:
          #   branches:
          #     only:
          #       - develop
  web:
    jobs:
      - test-web:
          filters:
            branches:
              ignore:
                - develop
  #     - storybook:
  #         filters:
  #           branches:
  #             only:
  #               - storybook
  #             ignore:
  #               - develop
  #     - push-dev-web:
  #         requires:
  #           - test-web
  #         filters:
  #           branches:
  #             ignore:
  #               - develop
  #     - push-prod-web:
  #         filters:
  #           branches:
  #             only:
  #               - develop
