version: 2
jobs:
  test:
    working_directory: ~/gobnb/client
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/gobnb
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Testing
          command: yarn snapshot
      # - run:
      #     name: Comparing Snapshots
      #     command: npx chromatic --project-token=r2o8ven87hs --exit-zero-on-changes
  docker_hub:
    working_directory: ~/app
    machine: true
    steps:
      - checkout:
      - run:
          name: Building Client Image
          command: docker build -t kokiebisu/gobnb-client ./client
      - run:
          name: Building Server Image
          command: docker build -t kokiebisu/gobnb-server ./server
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to Client
          command: docker push kokiebisu/gobnb-client
      - run:
          name: Pushing to Server
          command: docker push kokiebisu/gobnb-server

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - docker_hub:
          requires:
            - test
