version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    # Order list of run directives
    steps:
      # Pulls down the code to start a build
      - checkout
      - run:
          name: The First steps
          # | indicates there will be more than one line of shell commands
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Check Go version
          command: |
            go version
