version: 2
jobs:
  test-auth:
    working_directory: ~/airbnb/auth
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: testing
          command: yarn test:ci

  deploy-auth:
    working_directory: ~/app
    machine: true
    steps:
      - checkout:
      - run:
          name: building auth image
          command: docker build -t kokiebisu/nextbnb-auth ./auth
      - run:
          name: logging
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: pushing to docker hub
          command: docker push kokiebisu/nextbnb-auth

  test-stays:
    working_directory: ~/airbnb/stays
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: testing
          command: yarn test:ci

  deploy-stays:
    working_directory: ~/app
    machine: true
    steps:
      - checkout:
      - run:
          name: building stays image
          command: docker build -t kokiebisu/nextbnb-stays ./stays
      - run:
          name: logging
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: pushing to docker hub
          command: docker push kokiebisu/nextbnb-stays

  test-client:
    working_directory: ~/airbnb/client
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: installing dependencies
          command: yarn install
      - run:
          name: testing snapshot
          command: yarn snapshot
      - run:
          name: comparing snapshots
          command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes
  deploy-client:
    working_directory: ~/app
    machine: true
    steps:
      - checkout:
      - run:
          name: building client image
          command: docker build -t kokiebisu/nextbnb-client ./client
      - run:
          name: logging into docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: pushing to docker hub
          command: docker push kokiebisu/nextbnb-client

workflows:
  version: 2
  auth:
    jobs:
      - test-auth
      - deploy-auth:
          requires:
            - test-auth
  stays:
    jobs:
      - test-stays
      - deploy-stays:
          requires:
            - test-stays
  client:
    jobs:
      - test-client
      - deploy-client:
          requires:
            - test-client
