version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:11
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: cd client && yarn install
      - run:
          name: Testing
          command: cd client && yarn test
      - run:
          name: Comparing Snapshots
          command: cd client && npx chromatic --project-token=vnmckyhfm5k --exit-zero-on-changes
  docker_hub:
    working_directory: ~/app
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          docker build -t kokiebisu/gobnb-client ./client
          docker build -t kokiebisu/gobnb-server ./server
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push kokiebisu/gobnb-client ./client
          docker push kokiebisu/gobnb-server ./server
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - docker_hub:
          requires:
            - test
