version: 2
jobs:
  test-auth:
    working_directory: ~/airbnb/auth
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: testing
          command: yarn test

  test-stays:
    working_directory: ~/airbnb/stays
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: testing
          command: yarn test

  test-client:
    working_directory: ~/airbnb/client
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: testing snapshot
          command: yarn snapshot
      - run:
          name: comparing snapshots
          command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes
  docker_hub:
    working_directory: ~/app
    machine: true
    steps:
      - checkout:
      - run:
          name: Building Client Image
          command: docker build -t kokiebisu/airbnb-client ./client
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to Client
          command: docker push kokiebisu/airbnb-client

workflows:
  version: 2
  client:
    jobs:
      - test-client
      - docker_hub:
          requires:
            - test
  auth:
    jobs:
      - test-auth
  stays:
    jobs:
      - test-stay
