version: 2
jobs:
  test-auth:
    working_directory: ~/airbnb/packages/auth
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: testing
          command: yarn test:ci

  deploy-auth:
    working_directory: ~/airbnb/packages/auth
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: show path
          command: pwd
      - run:
          name: building auth image
          command: docker build -t kokiebisu/nextbnb-auth ./packages/auth
      - run:
          name: logging
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: pushing to docker hub
          command: docker push kokiebisu/nextbnb-auth

  test-stays:
    working_directory: ~/airbnb/packages/stays
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: testing
          command: yarn test:ci

  deploy-stays:
    working_directory: ~/airbnb/packages/stays
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building stays image
          command: docker build -t kokiebisu/nextbnb-stays ./packages/stays
      - run:
          name: logging
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: pushing to docker hub
          command: docker push kokiebisu/nextbnb-stays

  test-web:
    working_directory: ~/airbnb/packages/web
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: installing dependencies
          command: yarn install
      - run:
          name: testing snapshot
          command: yarn snapshot
      - run:
          name: comparing snapshots
          command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes
  deploy-web:
    working_directory: ~/airbnb/packages/web
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building web image
          command: docker build -t kokiebisu/nextbnb-web ./packages/web
      - run:
          name: logging into docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: pushing to docker hub
          command: docker push kokiebisu/nextbnb-web

workflows:
  version: 2
  auth:
    jobs:
      - test-auth
      - deploy-auth:
          requires:
            - test-auth
  stays:
    jobs:
      - test-stays
      - deploy-stays:
          requires:
            - test-stays
  web:
    jobs:
      - test-web
      - deploy-web:
          requires:
            - test-web
