version: 2.1
executors:
  test-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/airbnb
  image-executor:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/airbnb
commands:
  prepare:
    description: "Installs and builds the lerna environment"
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Install lerna
          command: yarn global add lerna -D -W
      - run:
          name: Install dependencies
          command: yarn bootstrap
      - run:
          name: Build packages
          command: yarn compile:packages
  docker-setup:
    parameters:
      image-name:
        type: string
      directory-path:
        type: string
    description: "Builds the docker image and pushes up to Dockerhub"
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Building <<parameters.directory-path>> image
          command: docker build -t <<parameters.image-name>> -f <<parameters.directory-path>> .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push <<parameters.image-name>>

jobs:
  test-auth:
    executor: test-executor
    steps:
      - prepare
      - run:
          name: Testing
          command: yarn test:auth
  push-prod-auth:
    executor: image-executor
    steps:
      - docker-setup:
          image-name: "kokiebisu/nextbnb-auth"
          directory-path: "./services/auth/Dockerfile"
  push-dev-auth:
    executor: image-executor
    steps:
      - docker-setup:
          image-name: "kokiebisu/nextbnb-auth-dev"
          directory-path: "./services/auth/dev.Dockerfile"
  test-stays:
    executor: test-executor
    steps:
      - prepare
      - run:
          name: Testing
          command: yarn test:stays
  push-prod-stays:
    executor: image-executor
    steps:
      - docker-setup:
          image-name: "kokiebisu/nextbnb-stays"
          directory-path: "./services/stays/Dockerfile"
  push-dev-stays:
    executor: image-executor
    steps:
      - docker-setup:
          image-name: "kokiebisu/nextbnb-stays-dev"
          directory-path: "./services/stays/dev.Dockerfile"
  test-web:
    executor: test-executor
    steps:
      - prepare
      - run:
          name: Testing
          command: yarn test:web
  storybook:
    executor: test-executor
    steps:
      - prepare
      - run:
          name: Testing snapshot
          command: yarn snapshot
      - run:
          name: Comparing snapshots
          command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes
  # push-prod-web:
  #   working_directory: ~/airbnb
  #   machine: true
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: Building web image
  #         command: docker build -t kokiebisu/nextbnb-web -f ./ui/web/Dockerfile .
  #     - run:
  #         name: Log in
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Pushing to docker hub
  #         command: docker push kokiebisu/nextbnb-web
  # push-dev-web:
  #   working_directory: ~/airbnb
  #   machine: true
  #   steps:
  #     - checkout:
  #         path: ~/airbnb
  #     - run:
  #         name: Building web image
  #         command: docker build -t kokiebisu/nextbnb-web-dev -f ./ui/web/dev.Dockerfile .
  #     - run:
  #         name: Log in
  #         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
  #     - run:
  #         name: Pushing to docker hub
  #         command: docker push kokiebisu/nextbnb-web-dev

workflows:
  version: 2
  auth:
    jobs:
      - test-auth:
          filters:
            branches:
              ignore:
                - develop
      - push-dev-auth:
          requires:
            - test-auth
          filters:
            branches:
              ignore:
                - develop
      - push-prod-auth:
          filters:
            branches:
              only:
                - develop
  stays:
    jobs:
      - test-stays:
          filters:
            branches:
              ignore:
                - develop
      - push-dev-stays:
          requires:
            - test-stays
          filters:
            branches:
              ignore:
                - develop
      - push-prod-stays:
          filters:
            branches:
              only:
                - develop
  web:
    jobs:
      - test-web:
          filters:
            branches:
              ignore:
                - develop
      - storybook:
          filters:
            branches:
              ignore:
                - develop
  #     - push-dev-web:
  #         requires:
  #           - test-web
  #         filters:
  #           branches:
  #             ignore:
  #               - develop
  #     - push-prod-web:
  #         filters:
  #           branches:
  #             only:
  #               - develop
