version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/client
    steps:
      # Pulls down the code to start a build
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      # - run: yarn build
      # - run: yarn netlify:deploy
