version: 2
jobs:
  test-auth:
    working_directory: ~/airbnb/services/auth
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Testing
          command: yarn test:ci

  deploy-auth:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building auth image
          command: docker build -t kokiebisu/nextbnb-auth -f ./services/auth/Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-auth

  test-stays:
    working_directory: ~/airbnb/services/auth
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Testing
          command: yarn test:ci

  deploy-stays:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building stays image
          command: docker build -t kokiebisu/nextbnb-stays -f ./services/stays/Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-stays

  test-web:
    working_directory: ~/airbnb/ui/web
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Testing snapshot
          command: yarn snapshot
      - run:
          name: Comparing snapshots
          command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes
  deploy-web:
    working_directory: ~/airbnb/ui/web
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Building web image
          command: docker build -t kokiebisu/nextbnb-web .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-web

workflows:
  version: 2
  auth:
    jobs:
      - test-auth
      - deploy-auth:
          requires:
            - test-auth
  stays:
    jobs:
      - test-stays
      - deploy-stays:
          requires:
            - test-stays
  web:
    jobs:
      - test-web
      - deploy-web:
          requires:
            - test-web
