version: 2
jobs:
  test:
    working_directory: ~/airbnb/client
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Testing
          command: yarn snapshot
      - run:
          name: Comparing Snapshots
          command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes
  docker_hub:
    working_directory: ~/app
    machine: true
    steps:
      - checkout:
      - run:
          name: Building Client Image
          command: docker build -t kokiebisu/airbnb-client ./client
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to Client
          command: docker push kokiebisu/airbnb-client

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - docker_hub:
          requires:
            - test
