version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      # Pulls down the code to start a build
      - checkout:
      - run: cd client && yarn install
      - run: cd client && yarn test
      - run: cd client && npx chromatic --project-token=vnmckyhfm5k --exit-zero-on-changes
workflows:
  approval:
    - ready:
        type: approval
        filters:
          branchs:
            ignore: master
    - chromatic/test:
        requires:
          - ready
  main-workflow:
    jobs:
      - chromatic/run-and-accept-all:
        filters:
          branches:
            only: master
