version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      # Pulls down the code to start a build
      - checkout:
      - run: ls -la
      - run: cd client && ls -la
      - run: cd client && yarn install && ls -la
      - run: cd client && yarn test && ls -la
      # - run: yarn build
      # - run: yarn netlify:deploy
