version: 2
jobs:
  test-auth:
    working_directory: ~/airbnb/services/auth
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Testing
          command: yarn test:ci

  push-prod-auth:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building auth image
          command: docker build -t kokiebisu/nextbnb-auth -f ./services/auth/Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-auth

  push-dev-auth:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building auth image
          command: docker build -t kokiebisu/nextbnb-auth-dev -f ./services/auth/dev.Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-auth-dev

  test-stays:
    working_directory: ~/airbnb/services/stays
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Testing
          command: yarn test:ci

  push-prod-stays:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building stays image
          command: docker build -t kokiebisu/nextbnb-stays -f ./services/stays/Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-stays

  push-dev-stays:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: building stays image
          command: docker build -t kokiebisu/nextbnb-stays-dev -f ./services/stays/dev.Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-stays-dev

  test-web:
    working_directory: ~/airbnb/ui/web
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Installing dependencies
          command: yarn install

  storybook:
    working_directory: ~/airbnb/ui/web
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Testing snapshot
          command: yarn snapshot
      - run:
          name: Comparing snapshots
          command: npx chromatic --project-token=e017nqnn22h --exit-zero-on-changes

  push-prod-web:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Building web image
          command: docker build -t kokiebisu/nextbnb-web -f ./ui/web/Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-web

  push-dev-web:
    working_directory: ~/airbnb
    machine: true
    steps:
      - checkout:
          path: ~/airbnb
      - run:
          name: Building web image
          command: docker build -t kokiebisu/nextbnb-web-dev -f ./ui/web/dev.Dockerfile .
      - run:
          name: Log in
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Pushing to docker hub
          command: docker push kokiebisu/nextbnb-web-dev

workflows:
  version: 2
  auth:
    jobs:
      - test-auth:
          filters:
            ignore:
              - master
      - push-dev-auth:
          requires:
            - test-auth
          filters:
            ignore:
              - master
      - push-prod-auth:
          filters:
            branches:
              only:
                - develop
  stays:
    jobs:
      - test-stays:
          filters:
            ignore:
              - master
      - push-dev-stays:
          requires:
            - test-stays
          filters:
            ignore:
              - master
      - push-prod-stays:
          filters:
            branches:
              only:
                - develop
  web:
    jobs:
      - test-web
      - storybook:
          filters:
            branches:
              only:
                - storybook
              ignore:
                - master
      - push-dev-web:
          requires:
            - test-web
          filters:
            ignore:
              - master
      - push-prod-web:
          filters:
            branches:
              only:
                - develop
