version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      # Pulls down the code to start a build
      - checkout:
      - run: cd client && yarn install
      - run: cd client && yarn test
