version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - db.env
    restart: always
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - gonebnb

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api:/usr/src/app/server
    depends_on:
      - db
    networks:
      - gonebnb

volumes:
  api:
  app:
  database_postgres:

networks:
  gonebnb:
    driver: bridge
