export const categories: {
  name: string;
  value: "artsCulture" | "outdoor" | "cabins" | "beach" | "popular";
}[] = [
  { name: "Desinations for arts & culture", value: "artsCulture" },
  { name: "Destinations for outdoor adventure", value: "outdoor" },
  { name: "Mountain cabins", value: "cabins" },
  { name: "Beach destinations", value: "beach" },
  { name: "Popular destinations", value: "popular" },
];

export const items = {
  artsCulture: [
    { city: "New York", location: "New York" },
    { city: "Phoenix", location: "Arizona" },
    { city: "Atlanta", location: "Georgia" },
    { city: "Chicago", location: "Illinois" },
    { city: "Miami", location: "Florida" },
    { city: "San Diego", location: "California" },
    { city: "San Francisco", location: "California" },
    { city: "Nashville", location: "Tennessee" },
    { city: "Seattle", location: "Washington" },
    { city: "Boston", location: "Masssachusetts" },
    { city: "Philadelphia", location: "Pennsylvania" },
    { city: "Dallas", location: "Texas" },
    { city: "Austin", location: "Texas" },
    { city: "Washington", location: "District of Columbia" },
    { city: "New Orleans", location: "Lousiana" },
    {
      city: "San Antonio",
      location: "Texas",
    },
    { city: "Houston", location: "Texas" },
    { city: "Los Angeles", location: "california" },
    { city: "London", location: "United Kingdom" },
    { city: "Paris", location: "France" },
    { city: "Memphis", location: "Tennessee" },
    { city: "Rome", location: "Italy" },
    { city: "Barcelona", location: "Spain" },
    { city: "Amsterdam", location: "Netherlands" },
    { city: "Lexington", location: "Kentucky" },
  ],
  outdoor: [
    { city: "New York", location: "New York" },
    { city: "Phoenix", location: "Arizona" },
    { city: "Atlanta", location: "Georgia" },
    { city: "chicago", location: "Illinois" },
    { city: "Miami", location: "Florida" },
    { city: "San Diego", location: "California" },
    { city: "San Francisco", location: "California" },
    { city: "Nashville", location: "Tennessee" },
    { city: "Seattle", location: "Washington" },
    { city: "Boston", location: "Masssachusetts" },
    { city: "Philadelphia", location: "Pennsylvania" },
    { city: "Dallas", location: "Texas" },
    { city: "Austin", location: "Texas" },
    { city: "Washington", location: "District of Columbia" },
    { city: "New Orleans", location: "Lousiana" },
    {
      city: "San Antonio",
      location: "Texas",
    },
    { city: "Houston", location: "Texas" },
    { city: "Los Angeles", location: "california" },
    { city: "London", location: "United Kingdom" },
    { city: "Paris", location: "France" },
    { city: "Memphis", location: "Tennessee" },
    { city: "Rome", location: "Italy" },
    { city: "Barcelona", location: "Spain" },
    { city: "Amsterdam", location: "Netherlands" },
    { city: "Lexington", location: "Kentucky" },
  ],
  cabins: [
    { city: "New York", location: "New York" },
    { city: "Phoenix", location: "Arizona" },
    { city: "Atlanta", location: "Georgia" },
    { city: "chicago", location: "Illinois" },
    { city: "Miami", location: "Florida" },
    { city: "San Diego", location: "California" },
    { city: "San Francisco", location: "California" },
    { city: "Nashville", location: "Tennessee" },
    { city: "Seattle", location: "Washington" },
    { city: "Boston", location: "Masssachusetts" },
    { city: "Philadelphia", location: "Pennsylvania" },
    { city: "Dallas", location: "Texas" },
    { city: "Austin", location: "Texas" },
    { city: "Washington", location: "District of Columbia" },
    { city: "New Orleans", location: "Lousiana" },
    {
      city: "San Antonio",
      location: "Texas",
    },
    { city: "Houston", location: "Texas" },
    { city: "Los Angeles", location: "california" },
    { city: "London", location: "United Kingdom" },
    { city: "Paris", location: "France" },
    { city: "Memphis", location: "Tennessee" },
    { city: "Rome", location: "Italy" },
    { city: "Barcelona", location: "Spain" },
    { city: "Amsterdam", location: "Netherlands" },
    { city: "Lexington", location: "Kentucky" },
  ],
  beach: [
    { city: "New York", location: "New York" },
    { city: "Phoenix", location: "Arizona" },
    { city: "Atlanta", location: "Georgia" },
    { city: "chicago", location: "Illinois" },
    { city: "Miami", location: "Florida" },
    { city: "San Diego", location: "California" },
    { city: "San Francisco", location: "California" },
    { city: "Nashville", location: "Tennessee" },
    { city: "Seattle", location: "Washington" },
    { city: "Boston", location: "Masssachusetts" },
    { city: "Philadelphia", location: "Pennsylvania" },
    { city: "Dallas", location: "Texas" },
    { city: "Austin", location: "Texas" },
    { city: "Washington", location: "District of Columbia" },
    { city: "New Orleans", location: "Lousiana" },
    {
      city: "San Antonio",
      location: "Texas",
    },
    { city: "Houston", location: "Texas" },
    { city: "Los Angeles", location: "california" },
    { city: "London", location: "United Kingdom" },
    { city: "Paris", location: "France" },
    { city: "Memphis", location: "Tennessee" },
    { city: "Rome", location: "Italy" },
    { city: "Barcelona", location: "Spain" },
    { city: "Amsterdam", location: "Netherlands" },
    { city: "Lexington", location: "Kentucky" },
  ],
  popular: [
    { city: "New York", location: "New York" },
    { city: "Phoenix", location: "Arizona" },
    { city: "Atlanta", location: "Georgia" },
    { city: "chicago", location: "Illinois" },
    { city: "Miami", location: "Florida" },
    { city: "San Diego", location: "California" },
    { city: "San Francisco", location: "California" },
    { city: "Nashville", location: "Tennessee" },
    { city: "Seattle", location: "Washington" },
    { city: "Boston", location: "Masssachusetts" },
    { city: "Philadelphia", location: "Pennsylvania" },
    { city: "Dallas", location: "Texas" },
    { city: "Austin", location: "Texas" },
    { city: "Washington", location: "District of Columbia" },
    { city: "New Orleans", location: "Lousiana" },
    {
      city: "San Antonio",
      location: "Texas",
    },
    { city: "Houston", location: "Texas" },
    { city: "Los Angeles", location: "california" },
    { city: "London", location: "United Kingdom" },
    { city: "Paris", location: "France" },
    { city: "Memphis", location: "Tennessee" },
    { city: "Rome", location: "Italy" },
    { city: "Barcelona", location: "Spain" },
    { city: "Amsterdam", location: "Netherlands" },
    { city: "Lexington", location: "Kentucky" },
  ],
};

export const destinationType = "artsCulture";
export const handleDestinationTypeChange = () =>
  alert("Should change destinationType");
export const handleDestinationRedirect = () =>
  alert("Should redirect to selected destination");
