export const $CARD = {
  category: 'category',
  horizontal: 'horizontal',
  vertical: 'vertical',
  typestay: 'typestay',
  arrangements: 'arrangements',
  checkin: 'checkin',
  review: 'review',
  stay: 'stay',
  nearby: 'nearby',
  online: 'online',
  participate: 'participate',
  available: 'available',
  host: 'host',
  set: 'set',
  again: 'again',
  works: 'works',
  sharing: 'sharing',
  how: 'how',
  anywhere: 'anywhere',
  hosting: 'hosting',
  video: 'video',
  starting: 'starting',
  collection: 'collection',
};
