export const title = 'Section Title';
export const description = 'Section Description';
export const pagination = false;
export const showAll = { description: 'Show all cards', to: '/' };
export const carouselType = '';
export const save = false;
export const isDescription = false;
export const fetchUrl = '';
export const items = new Array(8).fill(undefined);
