// jest.config.js
module.exports = {
  collectCoverageFrom: ["**/*.{ts,tsx}", "!**/*.d.ts", "!**/node_modules/**"],
  // we need to create this file
  setupFilesAfterEnv: ["<rootDir>/setupTests.js"],
  testPathIgnorePatterns: ["/node_modules/", "/.next/"],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/babel-jest",
  },
  transformIgnorePatterns: ["/node_modules/"],
  moduleNameMapper: {
    "\\.(css|less|scss)$": "identity-obj-proxy",
    "@bullet/(.*)": "<rootDir>/components/atoms/bullet/$1",
    "@bullet": "<rootDir>/components/atoms/bullet",
    "@input/(.*)": "<rootDir>/components/atoms/input/$1",
    "@input": "<rootDir>/components/atoms/input",
    "@button/(.*)": "<rootDir>/components/atoms/button/$1",
    "@button": "<rootDir>/components/atoms/button",
    "@bar/(.*)": "<rootDir>/components/organisms/bar/$1",
    "@bar": "<rootDir>/components/organisms/bar",
    "@video/(.*)": "<rootDir>/components/atoms/video/$1",
    "@video": "<rootDir>/components/atoms/video",
    "@card/(.*)": "<rootDir>/components/molecules/card/$1",
    "@card": "<rootDir>/components/molecules/card",
    "@footer/(.*)": "<rootDir>/components/organisms/footer/$1",
    "@footer": "<rootDir>/components/organisms/footer",
    "@styles/(.*)": "<rootDir>/styles/$1",
    "@svg/(.*)": "<rootDir>/public/svg/$1",
    "@animation/(.*)": "<rootDir>/components/animation/$1",
    "@animation": "<rootDir>/components/animation",
    "@helper/(.*)": "<rootDir>/helper/$1",
    "@particle/(.*)": "<rootDir>/components/particles/$1",
    "@template/(.*)": "<rootDir>/components/template/$1",
    "@template": "<rootDir>/components/template",
    "@prototype/(.*)": "<rootDir>/components/prototype/$1",
    "@prototype": "<rootDir>/components/prototype",
    "@layout/(.*)": "<rootDir>/components/layout/$1",
    "@layout": "<rootDir>/components/layout",
    "@panel/(.*)": "<rootDir>/components/molecules/panel/$1",
    "@panel": "<rootDir>/components/molecules/panel",
    "@hooks/(.*)": "<rootDir>/hooks/$1",
  },
  moduleDirectories: ["node_modules", "components"],
};
