apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-postgres
  template:
    metadata:
      labels:
        app: authentication-postgres
    spec:
      containers:
        - name: authentication-postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-postgres-service
spec:
  selector:
    app: authentication-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
