name: services-test

on: push

jobs:
  build:
    name: Auth Service Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: cd auth
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:ci
